<?php
// config/recipe_mappings.php

return [
    'ingredients' => [
        // ===== PROTEIN =====
        'daging sapi' => ['kategori' => 'protein', 'sub_kategori' => 'daging merah'],
        'daging kambing' => ['kategori' => 'protein', 'sub_kategori' => 'daging merah'],
        'ayam' => ['kategori' => 'protein', 'sub_kategori' => 'unggas'],
        'dada ayam' => ['kategori' => 'protein', 'sub_kategori' => 'unggas'],
        'paha ayam' => ['kategori' => 'protein', 'sub_kategori' => 'unggas'],
        'bebek' => ['kategori' => 'protein', 'sub_kategori' => 'unggas'],
        'ikan kembung' => ['kategori' => 'protein', 'sub_kategori' => 'ikan'],
        'ikan tuna' => ['kategori' => 'protein', 'sub_kategori' => 'ikan'],
        'ikan salmon' => ['kategori' => 'protein', 'sub_kategori' => 'ikan'],
        'udang' => ['kategori' => 'protein', 'sub_kategori' => 'seafood'],
        'cumi-cumi' => ['kategori' => 'protein', 'sub_kategori' => 'seafood'],
        'kepiting' => ['kategori' => 'protein', 'sub_kategori' => 'seafood'],
        'telur ayam' => ['kategori' => 'protein', 'sub_kategori' => 'telur'],
        'telur bebek' => ['kategori' => 'protein', 'sub_kategori' => 'telur'],
        'tempe' => ['kategori' => 'protein', 'sub_kategori' => 'kedelai'],
        'tahu' => ['kategori' => 'protein', 'sub_kategori' => 'kedelai'],
        'oncom' => ['kategori' => 'protein', 'sub_kategori' => 'kedelai'],
        'susu sapi' => ['kategori' => 'protein', 'sub_kategori' => 'susu'],
        'keju' => ['kategori' => 'protein', 'sub_kategori' => 'susu'],
        'hati ayam' => ['kategori' => 'protein', 'sub_kategori' => 'jeroan'],
        'usus sapi' => ['kategori' => 'protein', 'sub_kategori' => 'jeroan'],

        // ===== SAYURAN =====
        'bayam' => ['kategori' => 'sayuran', 'sub_kategori' => 'daun'],
        'kangkung' => ['kategori' => 'sayuran', 'sub_kategori' => 'daun'],
        'sawi hijau' => ['kategori' => 'sayuran', 'sub_kategori' => 'daun'],
        'sawi putih' => ['kategori' => 'sayuran', 'sub_kategori' => 'daun'],
        'kubis' => ['kategori' => 'sayuran', 'sub_kategori' => 'daun'],
        'selada' => ['kategori' => 'sayuran', 'sub_kategori' => 'daun'],
        'tomat' => ['kategori' => 'sayuran', 'sub_kategori' => 'buah'],
        'timun' => ['kategori' => 'sayuran', 'sub_kategori' => 'buah'],
        'terong' => ['kategori' => 'sayuran', 'sub_kategori' => 'buah'],
        'paprika' => ['kategori' => 'sayuran', 'sub_kategori' => 'buah'],
        'wortel' => ['kategori' => 'sayuran', 'sub_kategori' => 'umbi'],
        'kentang' => ['kategori' => 'sayuran', 'sub_kategori' => 'umbi'],
        'bawang merah' => ['kategori' => 'sayuran', 'sub_kategori' => 'umbi'],
        'bawang putih' => ['kategori' => 'sayuran', 'sub_kategori' => 'umbi'],
        'jahe' => ['kategori' => 'sayuran', 'sub_kategori' => 'rimpang'],
        'kunyit' => ['kategori' => 'sayuran', 'sub_kategori' => 'rimpang'],
        'lengkuas' => ['kategori' => 'sayuran', 'sub_kategori' => 'rimpang'],
        'kacang panjang' => ['kategori' => 'sayuran', 'sub_kategori' => 'kacang-kacangan'],
        'buncis' => ['kategori' => 'sayuran', 'sub_kategori' => 'kacang-kacangan'],
        'jagung' => ['kategori' => 'sayuran', 'sub_kategori' => 'biji'],

        // ===== KARBOHIDRAT =====
        'beras' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'beras'],
        'nasi' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'beras'],
        'beras merah' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'beras'],
        'tepung terigu' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'tepung'],
        'tepung beras' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'tepung'],
        'tepung tapioka' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'tepung'],
        'mie' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'mie'],
        'bihun' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'mie'],
        'roti' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'roti'],
        'singkong' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'umbi-umbian'],
        'ubi jalar' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'umbi-umbian'],
        'talon' => ['kategori' => 'karbohidrat', 'sub_kategori' => 'umbi-umbian'],

        // ===== BUMBU =====
        'cabai merah' => ['kategori' => 'bumbu', 'sub_kategori' => 'cabai'],
        'cabai rawit' => ['kategori' => 'bumbu', 'sub_kategori' => 'cabai'],
        'merica' => ['kategori' => 'bumbu', 'sub_kategori' => 'rempah'],
        'lada' => ['kategori' => 'bumbu', 'sub_kategori' => 'rempah'],
        'ketumbar' => ['kategori' => 'bumbu', 'sub_kategori' => 'rempah'],
        'jinten' => ['kategori' => 'bumbu', 'sub_kategori' => 'rempah'],
        'kemiri' => ['kategori' => 'bumbu', 'sub_kategori' => 'rempah'],
        'serai' => ['kategori' => 'bumbu', 'sub_kategori' => 'aromatik'],
        'daun jeruk' => ['kategori' => 'bumbu', 'sub_kategori' => 'aromatik'],
        'daun salam' => ['kategori' => 'bumbu', 'sub_kategori' => 'aromatik'],
        'laos' => ['kategori' => 'bumbu', 'sub_kategori' => 'rimpang'],

        // ===== LEMAK =====
        'minyak goreng' => ['kategori' => 'lemak', 'sub_kategori' => 'minyak'],
        'minyak kelapa' => ['kategori' => 'lemak', 'sub_kategori' => 'minyak'],
        'santan' => ['kategori' => 'lemak', 'sub_kategori' => 'santan'],
        'mentega' => ['kategori' => 'lemak', 'sub_kategori' => 'produk susu'],
        'margarin' => ['kategori' => 'lemak', 'sub_kategori' => 'produk susu'],

        // ===== PENYEDAP =====
        'garam' => ['kategori' => 'penyedap', 'sub_kategori' => 'dasar'],
        'gula pasir' => ['kategori' => 'penyedap', 'sub_kategori' => 'pemanis'],
        'gula merah' => ['kategori' => 'penyedap', 'sub_kategori' => 'pemanis'],
        'madu' => ['kategori' => 'penyedap', 'sub_kategori' => 'pemanis'],
        'penyedap rasa' => ['kategori' => 'penyedap', 'sub_kategori' => 'penguat rasa'],
        'kecap manis' => ['kategori' => 'penyedap', 'sub_kategori' => 'saus'],
        'kecap asin' => ['kategori' => 'penyedap', 'sub_kategori' => 'saus'],
        'saus tiram' => ['kategori' => 'penyedap', 'sub_kategori' => 'saus'],
        'terasi' => ['kategori' => 'penyedap', 'sub_kategori' => 'penguat rasa'],
    ],

    'aliases' => [
        // ===== PROTEIN ALIASES =====
        'daging sapi' => ['sapi', 'beef', 'daging merah', 'dageng sapi', 'daging lembu'],
        'daging kambing' => ['kambing', 'goat', 'gule kambing'],
        'ayam' => ['chicken', 'ayam negeri', 'ayam kampung', 'unggas'],
        'dada ayam' => ['fillet ayam', 'dada fillet', 'chicken breast'],
        'paha ayam' => ['paha atas', 'paha bawah', 'chicken thigh'],
        'ikan kembung' => ['kembung', 'ikan laut', 'mackerel'],
        'ikan tuna' => ['tuna', 'cakalang'],
        'udang' => ['prawn', 'shrimp', 'udang windu', 'udang rebon'],
        'cumi-cumi' => ['cumi', 'squid', 'sotong'],
        'telur ayam' => ['telur', 'endog', 'telur ayam negeri'],
        'tempe' => ['tempe kedelai', 'tempe bungkus'],
        'tahu' => ['tahu putih', 'tahu kuning', 'tofu'],

        // ===== SAYURAN ALIASES =====
        'bayam' => ['bayam hijau', 'bayam merah', 'spinach'],
        'kangkung' => ['kangkung darat', 'kangkung air', 'water spinach'],
        'sawi hijau' => ['sawi', 'caisim', 'pakcoy'],
        'sawi putih' => ['petsai', 'chinese cabbage'],
        'kubis' => ['kol', 'cabbage', 'kobis'],
        'tomat' => ['tomat merah', 'tomat buah', 'tomat sayur'],
        'timun' => ['mentimun', 'ketimun', 'cucumber'],
        'terong' => ['terong ungu', 'eggplant', 'brinjal'],
        'wortel' => ['wortel', 'carrot', 'wortel impor'],
        'kentang' => ['potato', 'kentang holland'],
        'bawang merah' => ['bamer', 'shallot', 'bawang bombay kecil'],
        'bawang putih' => ['baput', 'garlic', 'bwg putih', 'b.putih'],
        'jahe' => ['ginger', 'jahe emprit', 'jahe gajah'],
        'kunyit' => ['turmeric', 'kunyit bubuk', 'jenar'],
        'lengkuas' => ['laos', 'galangal', 'laos muda'],
        'kacang panjang' => ['kacang panjang hijau', 'yardlong bean'],
        'buncis' => ['green bean', 'kacang buncis'],
        'jagung' => ['jagung manis', 'corn', 'jagung rebus'],

        // ===== KARBOHIDRAT ALIASES =====
        'beras' => ['beras putih', 'padi', 'rice'],
        'nasi' => ['nasi putih', 'cooked rice'],
        'beras merah' => ['red rice', 'brown rice'],
        'tepung terigu' => ['terigu', 'flour', 'tepung protein tinggi'],
        'tepung beras' => ['rice flour', 'tepung kue'],
        'tepung tapioka' => ['tepung kanji', 'tapioca starch', 'aci'],
        'mie' => ['mi', 'noodles', 'mie kuning', 'mie telur'],
        'bihun' => ['rice vermicelli', 'mihun', 'soun'],
        'roti' => ['bread', 'roti tawar', 'roti gandum'],
        'singkong' => ['ketela', 'cassava', 'ubi kayu'],
        'ubi jalar' => ['sweet potato', 'ubi merah', 'ubi ungu'],

        // ===== BUMBU ALIASES =====
        'cabai merah' => ['cabe merah', 'red chili', 'lombok merah'],
        'cabai rawit' => ['cabe rawit', 'bird eye chili', 'lombok setan'],
        'merica' => ['pepper', 'lada hitam', 'black pepper'],
        'lada' => ['white pepper', 'lada putih', 'merica putih'],
        'ketumbar' => ['coriander', 'ketumbar bubuk'],
        'jinten' => ['cumin', 'jintan'],
        'kemiri' => ['candlenut', 'kemiri sangrai'],
        'serai' => ['sereh', 'lemongrass', 'serai wangi'],
        'daun jeruk' => ['jeruk purut', 'kaffir lime leaf'],
        'daun salam' => ['indonesian bay leaf', 'salam leaf'],

        // ===== LEMAK ALIASES =====
        'minyak goreng' => ['minyak sayur', 'cooking oil', 'minyak kelapa sawit'],
        'minyak kelapa' => ['coconut oil', 'virgin coconut oil'],
        'santan' => ['coconut milk', 'santan kental', 'santan encer'],
        'mentega' => ['butter', 'unsalted butter', 'mentega asin'],
        'margarin' => ['margarine', 'palm oil spread'],

        // ===== PENYEDAP ALIASES =====
        'garam' => ['salt', 'garam dapur', 'garam laut'],
        'gula pasir' => ['gula putih', 'sugar', 'gula kristal'],
        'gula merah' => ['gula jawa', 'palm sugar', 'gula aren'],
        'madu' => ['honey', 'madu murni'],
        'penyedap rasa' => ['msg', 'micin', 'vetsin', 'kaldu bubuk'],
        'kecap manis' => ['sweet soy sauce', 'kecap'],
        'kecap asin' => ['soy sauce', 'shoyu'],
        'saus tiram' => ['oyster sauce', 'saus tiram premium'],
        'terasi' => ['shrimp paste', 'terasi udang', 'belacan'],
    ],

    'health_restrictions' => [
        // ===== DIABETES =====
        'diabetes' => [
            'gula pasir' => ['severity' => 'hindari', 'notes' => 'Meningkatkan kadar gula darah secara cepat'],
            'gula merah' => ['severity' => 'hindari', 'notes' => 'Tetap mengandung glukosa tinggi'],
            'madu' => ['severity' => 'batasi', 'notes' => 'Gunakan dalam jumlah sangat sedikit'],
            'nasi' => ['severity' => 'batasi', 'notes' => 'Pilih porsi kecil, ganti dengan beras merah jika memungkinkan'],
            'beras' => ['severity' => 'batasi', 'notes' => 'Prioritaskan beras merah atau beras indeks glikemik rendah'],
            'tepung terigu' => ['severity' => 'batasi', 'notes' => 'Karbohidrat sederhana, dapat menaikkan gula darah'],
            'mie' => ['severity' => 'batasi', 'notes' => 'Terbuat dari tepung terigu, konsumsi secukupnya'],
            'roti' => ['severity' => 'batasi', 'notes' => 'Pilih roti gandum utuh, hindari roti manis'],
            'kentang' => ['severity' => 'batasi', 'notes' => 'Indeks glikemik sedang-tinggi'],
            'singkong' => ['severity' => 'batasi', 'notes' => 'Mengandung karbohidrat tinggi'],
            'ubi jalar' => ['severity' => 'anjuran', 'notes' => 'Indeks glikemik lebih rendah, kaya serat'],
            'beras merah' => ['severity' => 'anjuran', 'notes' => 'Kaya serat, indeks glikemik lebih rendah'],
        ],

        // ===== HIPERTENSI / DARAH TINGGI =====
        'hipertensi' => [
            'garam' => ['severity' => 'hindari', 'notes' => 'Natrium tinggi dapat meningkatkan tekanan darah'],
            'penyedap rasa' => ['severity' => 'hindari', 'notes' => 'Mengandung MSG dan natrium tinggi'],
            'kecap asin' => ['severity' => 'hindari', 'notes' => 'Kandungan garam sangat tinggi'],
            'kecap manis' => ['severity' => 'batasi', 'notes' => 'Mengandung garam dan gula'],
            'saus tiram' => ['severity' => 'batasi', 'notes' => 'Cek label, biasanya tinggi sodium'],
            'terasi' => ['severity' => 'batasi', 'notes' => 'Proses fermentasi dengan garam, tinggi sodium'],
            'daging sapi' => ['severity' => 'batasi', 'notes' => 'Pilih potongan tanpa lemak, hindari olahan'],
            'hati ayam' => ['severity' => 'batasi', 'notes' => 'Tinggi kolesterol dan purin'],
            'santan' => ['severity' => 'batasi', 'notes' => 'Lemak jenuh dapat mempengaruhi kesehatan jantung'],
            'minyak goreng' => ['severity' => 'batasi', 'notes' => 'Gunakan secukupnya, hindari gorengan berlebihan'],
            'bawang putih' => ['severity' => 'anjuran', 'notes' => 'Dapat membantu menurunkan tekanan darah'],
            'kunyit' => ['severity' => 'anjuran', 'notes' => 'Anti-inflamasi, baik untuk kesehatan jantung'],
        ],

        // ===== KOLESTEROL TINGGI =====
        'kolesterol tinggi' => [
            'daging sapi' => ['severity' => 'batasi', 'notes' => 'Pilih potongan lean, hindari jeroan'],
            'daging kambing' => ['severity' => 'batasi', 'notes' => 'Kandungan lemak jenuh cukup tinggi'],
            'hati ayam' => ['severity' => 'hindari', 'notes' => 'Kolesterol sangat tinggi'],
            'usus sapi' => ['severity' => 'hindari', 'notes' => 'Jeroan, kolesterol dan lemak tinggi'],
            'kuning telur' => ['severity' => 'batasi', 'notes' => 'Batasi 3-4 butir per minggu'],
            'udang' => ['severity' => 'batasi', 'notes' => 'Kolesterol tinggi meski rendah lemak'],
            'cumi-cumi' => ['severity' => 'batasi', 'notes' => 'Kandungan kolesterol cukup tinggi'],
            'kepiting' => ['severity' => 'batasi', 'notes' => 'Perhatikan cara masak, hindari santan kental'],
            'santan' => ['severity' => 'hindari', 'notes' => 'Lemak jenuh tinggi dapat meningkatkan LDL'],
            'mentega' => ['severity' => 'batasi', 'notes' => 'Lemak hewani jenuh'],
            'margarin' => ['severity' => 'batasi', 'notes' => 'Perhatikan kandungan trans fat'],
            'minyak goreng' => ['severity' => 'batasi', 'notes' => 'Gunakan minyak sehat, hindari pakai berulang'],
            'ikan salmon' => ['severity' => 'anjuran', 'notes' => 'Kaya omega-3, baik untuk kolesterol'],
            'ikan kembung' => ['severity' => 'anjuran', 'notes' => 'Sumber omega-3 yang terjangkau'],
            'tempe' => ['severity' => 'anjuran', 'notes' => 'Protein nabati, dapat membantu menurunkan kolesterol'],
            'tahu' => ['severity' => 'anjuran', 'notes' => 'Protein nabati rendah lemak'],
        ],

        // ===== ASAM URAT =====
        'asam urat' => [
            'hati ayam' => ['severity' => 'hindari', 'notes' => 'Purin sangat tinggi, memicu serangan asam urat'],
            'usus sapi' => ['severity' => 'hindari', 'notes' => 'Jeroan, kandungan purin tinggi'],
            'daging kambing' => ['severity' => 'hindari', 'notes' => 'Purin tinggi, berisiko memicu nyeri sendi'],
            'daging sapi' => ['severity' => 'batasi', 'notes' => 'Batasi porsi, pilih potongan tanpa lemak'],
            'udang' => ['severity' => 'batasi', 'notes' => 'Seafood mengandung purin sedang-tinggi'],
            'cumi-cumi' => ['severity' => 'batasi', 'notes' => 'Kandungan purin cukup tinggi'],
            'kepiting' => ['severity' => 'batasi', 'notes' => 'Seafood, konsumsi secukupnya'],
            'ikan kembung' => ['severity' => 'batasi', 'notes' => 'Ikan berlemak, purin sedang'],
            'kacang panjang' => ['severity' => 'batasi', 'notes' => 'Kacang-kacangan mengandung purin, tapi lebih aman dari jeroan'],
            'buncis' => ['severity' => 'batasi', 'notes' => 'Konsumsi dalam porsi wajar'],
            'tempe' => ['severity' => 'anjuran', 'notes' => 'Protein nabati, purin lebih rendah dari hewani'],
            'tahu' => ['severity' => 'anjuran', 'notes' => 'Aman dikonsumsi dalam porsi normal'],
            'sayuran hijau' => ['severity' => 'anjuran', 'notes' => 'Kaya serat, membantu pengeluaran asam urat'],
            'jahe' => ['severity' => 'anjuran', 'notes' => 'Anti-inflamasi alami, bantu redakan nyeri'],
        ],

        // ===== MAAG / GERD / ASAM LAMBUNG =====
        'maag' => [
            'cabai merah' => ['severity' => 'hindari', 'notes' => 'Pedas dapat mengiritasi lambung'],
            'cabai rawit' => ['severity' => 'hindari', 'notes' => 'Sangat pedas, memicu naiknya asam lambung'],
            'merica' => ['severity' => 'batasi', 'notes' => 'Rempah pedas, gunakan sedikit saja'],
            'lada' => ['severity' => 'batasi', 'notes' => 'Dapat memicu iritasi lambung jika berlebihan'],
            'bawang putih' => ['severity' => 'batasi', 'notes' => 'Konsumsi mentah dapat memicu heartburn'],
            'jahe' => ['severity' => 'anjuran', 'notes' => 'Membantu meredakan mual, gunakan secukupnya'],
            'kunyit' => ['severity' => 'anjuran', 'notes' => 'Antasida alami, baik untuk lambung'],
            'santan' => ['severity' => 'batasi', 'notes' => 'Lemak tinggi dapat memperlambat pengosongan lambung'],
            'minyak goreng' => ['severity' => 'batasi', 'notes' => 'Makanan berminyak sulit dicerna'],
            'tempe' => ['severity' => 'anjuran', 'notes' => 'Protein nabati mudah dicerna, fermentasi baik untuk pencernaan'],
            'tahu' => ['severity' => 'anjuran', 'notes' => 'Tekstur lembut, mudah dicerna'],
            'nasi' => ['severity' => 'anjuran', 'notes' => 'Karbohidrat netral, baik untuk penderita maag'],
            'pisang' => ['severity' => 'anjuran', 'notes' => 'Membantu menetralkan asam lambung'],
        ],

        // ===== GINJAL =====
        'gagal ginjal' => [
            'garam' => ['severity' => 'hindari', 'notes' => 'Pembatasan natrium sangat penting'],
            'penyedap rasa' => ['severity' => 'hindari', 'notes' => 'Tinggi sodium dan fosfor'],
            'kecap asin' => ['severity' => 'hindari', 'notes' => 'Kandungan garam sangat tinggi'],
            'daging sapi' => ['severity' => 'batasi', 'notes' => 'Protein hewani perlu dibatasi, konsultasi dokter'],
            'susu sapi' => ['severity' => 'batasi', 'notes' => 'Tinggi fosfor dan kalium'],
            'keju' => ['severity' => 'hindari', 'notes' => 'Tinggi sodium, fosfor, dan protein'],
            'kentang' => ['severity' => 'batasi', 'notes' => 'Tinggi kalium, perlu direndam sebelum dimasak'],
            'tomat' => ['severity' => 'batasi', 'notes' => 'Kandungan kalium cukup tinggi'],
            'bayam' => ['severity' => 'batasi', 'notes' => 'Tinggi oksalat dan kalium'],
            'tempe' => ['severity' => 'batasi', 'notes' => 'Protein nabati, tapi perhatikan porsi'],
            'putih telur' => ['severity' => 'anjuran', 'notes' => 'Sumber protein rendah fosfor'],
        ],

        // ===== ALERGI / INTOLERANSI =====
        'alergi seafood' => [
            'udang' => ['severity' => 'hindari', 'notes' => 'Alergen utama, hindari total'],
            'cumi-cumi' => ['severity' => 'hindari', 'notes' => 'Moluska, berisiko reaksi alergi'],
            'kepiting' => ['severity' => 'hindari', 'notes' => 'Krustasea, alergen kuat'],
            'ikan tuna' => ['severity' => 'batasi', 'notes' => 'Cek toleransi individu, beberapa orang alergi ikan'],
            'terasi' => ['severity' => 'hindari', 'notes' => 'Terbuat dari udang, mengandung alergen seafood'],
        ],

        'intoleransi laktosa' => [
            'susu sapi' => ['severity' => 'hindari', 'notes' => 'Mengandung laktosa'],
            'keju' => ['severity' => 'batasi', 'notes' => 'Pilih keju aged yang rendah laktosa'],
            'mentega' => ['severity' => 'anjuran', 'notes' => 'Kadar laktosa sangat rendah, umumnya aman'],
            'santan' => ['severity' => 'anjuran', 'notes' => 'Alternatif non-dairy yang aman'],
        ],
    ],
];